### ISSUE TITLE
Update graphic icons for Our Services - color

### ISSUE THREAD

**Issue by alexrekas** [ideacrew/idc-web#10]
similar to ideacrew/ic-web#81 ,replace old ideacrew bright blue (#3493ff) in the svgs with blue-035 - rgb (33, 91, 143);

**Comment by bbodine1** [comment]
@alexrekas I need help figuring this one out. Can you help?

**Comment by alexrekas** [comment]
@bbodine1 the blue used in the graphics for the section "Our Services" within the "About" page uses a blue (#3493ff) and we want to replace it with "blue-035 - rgb (33, 91, 143);"

![Image](https://github.com/ideacrew/idc-web/assets/3810583/9b4ff8e1-5244-4129-927a-4065a2dc37c5)
