### ISSUE TITLE
Homepage Clients: Each logo should be same size optically

### ISSUE THREAD

**Issue by alexrekas** [ideacrew/idc-web#33]
images need to be reworked to ensure that each of them look visually the same size and aligned properly.

**Comment by bbodine1** [comment]
This issue will require access to ideacrews [cloudinary](https://cloudinary.com/users/login) account.

I need to get admin permission from the account holder.... not sure yet who that is.

**Comment by alexrekas** [comment]
This was likely done with the previous owner, I've just created an account and added you as an admin (you should receive an email about it). We may need to reconnect this with our new accounts and reupload images.

**Comment by bbodine1** [comment]
@alexrekas  I'm connected to the new cloudinary account. We just need to add the images up there and I will get these switched out on the website.

We could add the assets in directly without the need for cloudinary. We don't gain much by using the CDN to serve the images.

What are your thoughts?

**Comment by bbodine1** [comment]
@alexrekas Will this work? It's a quick css adjustment rather than reworking the design or adjusting images.

## Proposed


![Image](https://github.com/ideacrew/idc-web/assets/2924609/840ef064-62b0-4be6-b3f6-f7c9e861960d)



## Current


![Image](https://github.com/ideacrew/idc-web/assets/2924609/8aebb057-6e3c-4843-a5ab-a6a1a44c5e68)

**Comment by alexrekas** [comment]
@bbodine1 Yeah, that looks good, I'm fine with moving away from cloudinary if it doesn't help that much. that being said, even if it helps a little with speed, I'd like to keep it only bc I love how fast our site is currently. I will leave that decision up to you though.

The proposed changes look good to me, thank you!
