### ISSUE TITLE
Spacing on "expand/collapse all modueles" 

### ISSUE THREAD

**Issue by alexrekas** [ideacrew/idc-web#9]
Add `padding-bottom:1rem;` to the "buttons". 

Also, why are these <button>'s and not <a>?

**Comment by bbodine1** [comment]
@alexrekas Is this what you mean?

![image](https://github.com/ideacrew/idc-web/assets/2924609/9a574ea6-803b-4c61-b362-13410eecf3eb)

**Comment by alexrekas** [comment]
@bbodine1 Yes, those links - though it should be `margin-bottom:1rem;` and not `padding-bottom:1rem;`
I'm unsure what I meant by "Also, why are these 's and not ?", so disregard that.
